### ISSUE TITLE
Dockerfile issue 

### ISSUE THREAD

**Issue by IfedayoVLSI** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#1]
there is an issue with the git --recursive command

**Comment by ddddbqq** [comment]
you can download the git codes manually and use a copy command to build the app/ dir in docker

**Comment by IfedayoVLSI** [comment]
> you can download the git codes manually and use a copy command to build the app/ dir in docker

yea that would work but the docker files need some edits I have been able to use it after I made some few edits

**Comment by bingyuew** [comment]
Thank you for pointing that out. Please test the updated dockerfile.

**Comment by IfedayoVLSI** [comment]
okay thanks, I wrote my own docker file. the --recursive is an old github command and it has been replaced with --recurse-submodule

Best regards,

Ifedayo Akinfemisoye
Graduate Research Assistant
Electrical and Computer Engineering
VLSI CAD lab

________________________________
