### ISSUE TITLE
Can we perform gate sizing on Macro or not?

### ISSUE THREAD

**Issue by steveniscoming** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#10]
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/135108873/f81ae31b-827d-4660-aad3-b0d61df8a887)
we wonna know if we can perform gate sizing on Macro or not

**Comment by bingyuew** [comment]
Sequential gate sizing will not be permitted. Sizing of macros or sram cells will not be permitted.

**Comment by bingyuew** [comment]
@steveniscoming Please confirm if the question is solved. If so, please close the issue. Thanks.
