### ISSUE TITLE
'Timing' object has no attribute 'resetTiming'

### ISSUE THREAD

**Issue by steveniscoming** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#11]
when I execute the new example I have some problem
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/135108873/99fb9dfd-18c7-40e2-939a-35b0964beb10)
(I have rebuilt my openroad yesterday)

**Comment by bingyuew** [comment]
Please run "git pull --recurse-submodules" or reclone the GitHub repository and rebuild the OpenROAD binary. Please make sure you are using the OpenROAD module from my fork.

**Comment by steveniscoming** [comment]
I used this command "git clone --recursive https://github.com/bingyuew/OpenROAD.git"
is it correct?

**Comment by bingyuew** [comment]
No, it will link to the default branch. Please add the "-b cad_contest" flag to specify the branch. Or use the command I provided above.

**Comment by steveniscoming** [comment]
got it
