### ISSUE TITLE
Queries about src/evaluation/evaluation.py

### ISSUE THREAD

**Issue by pipiofzl** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#14]
I encountered an issue while using src/evaluation/evaluation.py. Specifically, when performing two consecutive ICCAD_evaluation calculations in evaluation.py, as shown in the script below (The modifications made in evaluation.py are as shown in the screenshot. Everything else is identical to the evaluation.py on GitHub.):
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/87072615/e1ab463e-cfd1-477a-94f2-f74ba37d0639)
I noticed that evaluating test_1.size first, then output.size, and vice versa, leads to completely different scores. What could be causing this issue? 
(PS: The mentioned output.size is the result for the given NV_NVDLA_partition_m design without any replacements, while test_1.size is the result after replacing the cell corresponding to the “g85390” instance in the NV_NVDLA_partition_m design with equiv_cells[2].)
Below are the result images:
First evaluate test_1.size and then evaluate output.size：
test_1.size:
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/87072615/2e15ac56-c03d-4e42-849d-897df0d7c359)
output.size:
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/87072615/8976dfd4-f3ef-48c2-a8fb-2a2ab7cde356)
First evaluate output.size and then evaluate test_1.size：
output.size:
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/87072615/1ee20fcf-b17d-49ec-86d6-8c9f1acddd7b)
test_1.size:
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/87072615/292a663c-2047-4509-8586-8ef32388d9b5)
Here is the Google Drive link where I have placed output.size and test_1.size.
https://drive.google.com/drive/folders/1iTMICfo8Uag5hXgdlTT-fJxCVhQ2fsp_?usp=sharing

**Comment by bingyuew** [comment]
I cannot reproduce the timing number you are getting. Besides, OpenROAD can only read one design at a time. You will receive an error message if you try to load the design twice.

**Comment by pipiofzl** [comment]
Are the results the same when you first run test_1.size and then output.size compared to running output.size first and then test_1.size?

**Comment by pipiofzl** [comment]
Can evaluation.py only evaluate one .size file at a time? If I want to evaluate two .size files, how should I do it?

**Comment by bingyuew** [comment]
Unfortunately, openroad does not support this feature.

**Comment by pipiofzl** [comment]
OK，thanks~
