### ISSUE TITLE
questions about alpha submission

### ISSUE THREAD

**Issue by kinling9** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#15]
There are several questions about alpha submission:
1. Is the upload location of the docker image the TSRI machine mentioned in the email?
2. The calling method of the submission. Considering that there are no clear requirements in the PDF, must it be specified in the readme?
3. The location of the benchmark. Will all benchmarks locate in /app/design?

**Comment by bingyuew** [comment]
You should receive a separate email regarding the alpha resubmission.

**Comment by kinling9** [comment]
> You should receive a separate email regarding the alpha resubmission.
We have received it, thank you
