### ISSUE TITLE
Aalpha submission question

### ISSUE THREAD

**Issue by steveniscoming** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#16]
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/135108873/4f2d26e1-49c0-4ad7-a0eb-129cde6afcd5)
Could you please explain in more detail what "The Dockerfile must be built on this existing provided Dockerfile" means?

**Comment by bingyuew** [comment]
@steveniscoming You can add any modules required for your sizer to the Dockerfile, but you cannot delete or modify anything in the original one, including the version.

**Comment by steveniscoming** [comment]
So it means I have to copy the provided docker first ,then added the modules or commands to be the new docker  ?

**Comment by bingyuew** [comment]
What I mean is that I cannot guarantee that tools like OpenROAD and CircuitOps will work correctly if you change the package versions we provided. For the submission, you only need to upload the Docker image. The provided Dockerfile contains the settings that work fine on the Nvidia server. You can build on top of it to create your Docker image.

**Comment by steveniscoming** [comment]
so i don't need to do such thing
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/135108873/e8f77c6d-f77d-4d80-ab5e-b76cb79274a2)
in my dockerfile

**Comment by bingyuew** [comment]
You need to clone the github repo and build the openroad binary so I can run the evaluation.

**Comment by steveniscoming** [comment]
So I still have to git clone the "2024_ICCAD_Contest_Gate_Sizing_Benchmark "directory to download the Openroad , design and platform  ?

**Comment by bingyuew** [comment]
Please follow the instructions in the document. I have specified the script format in the doc. I cannot guarantee that your submission will be evaluated correctly if you choose another approach to build the docker image.

**Comment by steveniscoming** [comment]
Many thanks
