### ISSUE TITLE
Question about alpha submission

### ISSUE THREAD

**Issue by vickychen928** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#17]
I would like to ask if Python script files only accept the parameters listed below? (lef, lib, def, IR_Table, output) Am I allowed to add other parameters, such as "sdc"? 

![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/84194000/5cf468dd-a3c5-4145-b7b9-45effa8cedbe)

**Comment by bingyuew** [comment]
You can assume the sdc files follow the same naming convention and path as the def file. So for the public and hidden cases, there will be a def and an sdc file under the /app/2024_ICCAD_Contest_Gate_Sizing_Benchmark/design/${design_name}/ path. The DEF will be named "${design_name}.def", and the SDC will be named "${design_name}.sdc". You can also refer to the "setRC.tcl" script in the /app/2024_ICCAD_Contest_Gate_Sizing_Benchmark/platform/ASAP7/ path.

**Comment by vickychen928** [comment]
So, does this mean I can add arbitrary arguments in the Python script under the condition that the input argument in ICCAD24_sizer.sh is only $design_name?

**Comment by bingyuew** [comment]
Will get back to you shortly.

**Comment by steveniscoming** [comment]
Is the execution command for each design "./ICCAD24_sizer.sh <design_name>"?

**Comment by bingyuew** [comment]
We state "The submission should contain a top-level  "ICCAD24_sizer.sh" in the /app/sizer directory which takes the design name as the ONLY input argument and runs one of the following commands based on your use case." in the doc.

And the following commands are just examples. You are allowed to modify them, such as adding more flags, as long as the top-level "ICCAD24_sizer.sh" script only takes the design name as the only input.

**Comment by bingyuew** [comment]
@vickychen928 The command will be "time ./ICCAD24_sizer.sh <design_name>"

**Comment by vickychen928** [comment]
Thank you!
