### ISSUE TITLE
Questuion about the hidden cases

### ISSUE THREAD

**Issue by steveniscoming** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#18]
Do the hidden designs also include ".size" file?

**Comment by bingyuew** [comment]
The hidden cases and the corresponding .size files will be released after the contest.

**Comment by steveniscoming** [comment]
So there won't be ".size" file in each design directory during the alpha test ?

**Comment by bingyuew** [comment]
We will only provide the .size files for the public benchmarks during the alpha, beta, and final evaluations. The .size files for the hidden benchmarks will be released after the contest. During the evaluation process, we will not provide the .size files for the hidden benchmarks.

**Comment by steveniscoming** [comment]
thanks
