### ISSUE TITLE
Output file question

### ISSUE THREAD

**Issue by steveniscoming** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#20]
![image](https://github.com/user-attachments/assets/4a70a683-00e3-41c7-aa67-51bea3940d8c)
In this response, you mention that the .size file does not need to have all gates in the circuit.
But, in the alpha test response we get the comment "Error: Instance "ADD_TC_OP28469_g11971" is not in the output .size file"
![image](https://github.com/user-attachments/assets/52c2df61-48d4-40d9-bdd9-5b7a3603a978)
why would it be an error if we don't put "ADD_TC_OP28469_g11971" in our .size file.

**Comment by bingyuew** [comment]
Hi @steveniscoming , the question was answered after the alpha submission deadline. To ensure the fairness of the alpha evaluation, we used the sample evaluation script during the alpha stage, which requires all gates to be presented in the file. However, for the upcoming beta and final stages, you can follow the answer provided in Q&A No. 30.

**Comment by steveniscoming** [comment]
Got it thank u
