### ISSUE TITLE
Definitions of runTimeF and cutoff runtime

### ISSUE THREAD

**Issue by pipiofzl** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#22]
Dear Organizers,

I have three questions that I would like to ask:

For the alpha test case scores, could you please clarify if the "runtime of code" score has a specific unit of measurement? Is it in seconds, minutes, or hours?

I have some confusion regarding Problem C. In the evaluation section of Problem C, it mentions the runTimeF in the formula. Could you please confirm whether this runTimeF refers to the time taken to **evaluate** the .size file or the time taken to **generate** the .size file? Additionally, is this runTimeF presented as a relative score or as the actual computed time?

Lastly, regarding the statement "The cutoff runtime is 2 hours" in the evaluation section of Problem C, does this 2-hour limit apply to the time for **generating** the .size file or the time for **evaluating** the .size file?

Thank you for your assistance with these questions.

**Comment by bingyuew** [comment]
1. They are in seconds.
2. It's the time to generate the .size file, and it's the actual runtime.
3. The 2 hour limit is for both generating the .size file and evaluating the .size file.

**Comment by bingyuew** [comment]
We have addressed this in QA No.19, 22, and 24.
If this answers your question, please close the issue.

**Comment by pipiofzl** [comment]
> The 2 hour limit is for both generating the .size file and evaluating the .size file.

I would like to confirm that the 2-hour limit applies respectively to generating the .size file and to the evaluation process. Does this mean that the total runtime will be 2+2=4 hours?

**Comment by bingyuew** [comment]
Yes. The evaluation time for each case is 4 hours.

**Comment by pipiofzl** [comment]
I would like to confirm: if my generation program runs for 4 hours without stopping, will this prevent the evaluation process from being completed, even if the .size file is generated? In other words, are the generation program and evaluation process run consecutively within a total 4-hour limit, rather than being separate phases?

**Comment by bingyuew** [comment]
The .size file generation and evaluation process is run separately, each with a 2-hour limit.

**Comment by pipiofzl** [comment]
I would like to clarify whether the 2-hour limit means that if the program doesn't terminate within 2 hours, it will be considered that we failed to generate the .size file. In our tests, the .size file is always created within 2 hours, but the program may not fully complete its run within that time. In this case, would it still be considered as not having generated the .size file? Also, should the .size file be placed in the /app/sizer directory?

Thank you for your clarification.

**Comment by bingyuew** [comment]
For generating the .size file: If the .size file can be generated within the 2-hour limit, then your .size file will be put into evaluation, regardless of whether the program is killed due to the runtime limit or not. If the program is terminated due to the runtime limit, then the runtime for your sizer is considered as 7200 seconds.

For evaluating the .size file: Even if you successfully generate a .size file, you must still manage to complete the evaluation process within the 2-hour limit. If your .size file fails to pass the legalization process or fails to complete the global routing stage due to high overflow, then it is still considered a failed case.

The .size file should be put under the /app/sizer/output directory.

**Comment by bingyuew** [comment]
@pipiofzl If this answers your question, please close the issue.
