### ISSUE TITLE
'Timing' object has no attribute 'getMaxSlewLimit'

### ISSUE THREAD

**Issue by Yufan-Du** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#3]
<img width="893" alt="Screenshot 2024-06-09 at 21 56 45" src="https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/97397289/bf0a5ad3-b96a-4477-a4f0-a85688330622">
It looks like I already used the latest  OpenROAD version, but it still doesn't contain these methods.

**Comment by bingyuew** [comment]
Please update the submodule and build again

**Comment by bingyuew** [comment]
@Yufan-Du please confirm if the issue is solved.

**Comment by VidyaChhabria** [comment]
@Yufan-Du Is this issue resolved? We would like to close the issues as resolved.
