### ISSUE TITLE
bug in evalutaion.py

### ISSUE THREAD

**Issue by cai-zhi-jie** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#4]
in 2024_ICCAD_Contest_Gate_Sizing_Benchmark/src/evaluation/evaluation.py line 69 -- 82 when getting the max cap and slew:
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/73417581/f0c23c76-0698-42fe-baa2-33d63b6259f6)
capLimit is wrongly assigned with the value of slewLimit in line 82.
And the slewLimit is hardcore set to 320 in line 91.

Since the result of "report_check_types -max_slew," the reported limit should be the slew limit. 
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/73417581/5f6f9a1a-744c-46ad-a616-0a50ef802fe7)

Meanwhile, the capLimit can be acquired in the result of "report_check_types -max_cap"
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/73417581/fb92b5fe-d869-4fb4-90df-a6f412e72dc3)

**Comment by bingyuew** [comment]
Fixed that.
