### ISSUE TITLE
OpenROAD_example.py can't be valid for new Benchmark

### ISSUE THREAD

**Issue by steveniscoming** [ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark#6]
when I use the following command on new benchmark 
../../OpenROAD/build/src/openroad -python OpenROAD_example.py --design_name NV_NVDLA_partition_p
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/135108873/24b99f55-0366-4091-8119-295fdcea7a51)
I come across some problems
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/135108873/6877e623-9351-4944-9e69-fd30a5a963a3)
same things happen to other new benchmark 
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/135108873/f0fd6f87-6c56-4a87-97b7-2cc03098e981)
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/135108873/4d5b4a30-3cef-4505-9756-24eb2e1099cc)

but the original one (NV_NVDLA_partition_m)does not have such  problem
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/135108873/c6f860d4-b4cb-4495-9625-cfd972bb332e)
![image](https://github.com/ASU-VDA-Lab/2024_ICCAD_Contest_Gate_Sizing_Benchmark/assets/135108873/b6c052fe-8431-4594-80a4-7619ffc0de25)

**Comment by bingyuew** [comment]
The example file is tailor-made for the nvdla_partition_m case. You need to change the instance name used in the "findInst" function to work with other designs.

**Comment by steveniscoming** [comment]
Got it thanks
